added test scenarios for amazon login page
cpataltmetrik/webdriveriowithtypescript pull request #17
Opened 2022-04-19 13:15 UTC by prem225

2022-04-20 04:23 UTC, cpataltmetrik reviewed
@prem225  can you please make sure that logger has been added to your each action.

2022-04-20 09:26 UTC, balualtimetrik requested changes

2022-04-20 09:26 UTC, balualtimetrik commented on config-wdio/wdio.local.conf.ts
> +    logLevel: 'silent',
log level should be info

2022-04-20 09:26 UTC, balualtimetrik commented on src/main/pageobjects/amz.login.page.ts
> +        }
these are all test case steps, please put them in test case file. Page object pages should only contain locators and related actions.

2022-04-21 07:35 UTC, prem225 commented on config-wdio/wdio.local.conf.ts
> +    logLevel: 'silent',
Done Balu

2022-04-22 06:00 UTC, balualtimetrik commented on src/main/pageobjects/login.page.ts
> +        }
Put this method in test case and add assertion instead of If condition.  Dont use console.log use addLogger utility

2022-04-22 06:00 UTC, balualtimetrik commented on test/specs/login.spec.ts
> +        await login.loginSucces()
rename test case to "should verify login is successful or not" and add the above page code here.

2022-04-22 10:52 UTC, balualtimetrik commented on test/specs/login.spec.ts
> +            await login.successLog.highlightElement()
please add an assertion instead of If block.

2022-04-27 08:45 UTC, balualtimetrik approved these changes

2022-04-27 08:45 UTC, merged